### ISSUE TITLE
3511 compilation notes from SBCL

### ISSUE THREAD

**Issue by snunez1** [Lisp-Stat/statistics#1]
When compiling  with SBCL, 3511 notes are printed.  These are mostly optimisation warnings. See attached file.

Generally I've found SBCL's warnings of this kind to be accurate.  Kind of a 'lint' for common lisp and, like 'lint', one code fix can suppress many warnings.  Probably worth looking into.

[compile-notes.txt](https://github.com/Lisp-Stat/statistics/files/9343998/compile-notes.txt)

**Comment by LEHunter** [comment]
I skimmed through them.  Every one (on the first 20 pages or so) was a note about being unable to open code a coercion due to type uncertainty.  But that’s a feature, not a bug.  The functions all take arbitrary inputs, do input tests specific to the calculation, and then coerce and provide declarations so that the actual calculations can be optimized.  In general, I find the calculations to be quite fast, even for very large inputs…

Larry

On Aug 15, 2022, at 3:06 PM, Steve Nunez ***@***.******@***.***>> wrote:

[External Email - Use Caution]


When compiling with SBCL, 3511 notes are printed. These are mostly optimisation warnings. See attached file.

Generally I've found SBCL's warnings of this kind to be accurate. Kind of a 'lint' for common lisp and, like 'lint', one code fix can suppress many warnings. Probably worth looking into.

compile-notes.txt<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLisp-Stat%2Fstatistics%2Ffiles%2F9343998%2Fcompile-notes.txt&data=05%7C01%7CLARRY.HUNTER%40CUANSCHUTZ.EDU%7Cceb5c1ca7f07424bc77a08da7f2383f6%7C563337caa517421aaae01aa5b414fd7f%7C0%7C0%7C637962087764850866%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GX267Xawl%2FKV3eDbXqFTECfDDZvcup2EyTsTTPCFz2A%3D&reserved=0>

**Comment by snunez1** [comment]
OK, I'll close this and put a note in the readme repeating what you said.  That way if (when), someone is tempted to report the issues they'll know why things are the way they are.
